# Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
#
# This file is part of eProsima Fast DDS Monitor.
#
# eProsima Fast DDS Monitor is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# eProsima Fast DDS Monitor is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with eProsima Fast DDS Monitor. If not, see <https://www.gnu.org/licenses/>.

macro(check_stdcxx)

    # Note that FASTDDS_REQUIRED_FLAGS provides access to the compiler flags in the try-compile testing like
    # CheckLibatomic module
    include(CheckCXXCompilerFlag)

    if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_CLANG OR
        CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR
        CMAKE_CXX_COMPILER_ID MATCHES "QCC")
        check_cxx_compiler_flag(-std=c++20 SUPPORTS_CXX20)
        set(HAVE_CXX20 0)
        set(HAVE_CXX17 0)
        set(HAVE_CXX14 0)
        set(HAVE_CXX1Y 0)
        set(HAVE_CXX11 0)
        set(HAVE_CXX0X 0)
        if(SUPPORTS_CXX20 AND (NOT FORCE_CXX OR "${FORCE_CXX}" STREQUAL "20"))
            set(FASTDDS_REQUIRED_FLAGS "-std=c++20 ${FASTDDS_REQUIRED_FLAGS}")
            add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-std=c++20>)
            set(HAVE_CXX20 1)
            set(HAVE_CXX17 1)
            set(HAVE_CXX14 1)
            set(HAVE_CXX1Y 1)
            set(HAVE_CXX11 1)
            set(HAVE_CXX0X 1)
        elseif(NOT SUPPORTS_CXX20 AND FORCE_CXX AND "${FORCE_CXX}" STREQUAL "20")
            message(FATAL_ERROR "Force to support stdc++20 but not supported by the compiler")
        else()
            check_cxx_compiler_flag(-std=c++17 SUPPORTS_CXX17)
            if(SUPPORTS_CXX17 AND (NOT FORCE_CXX OR "${FORCE_CXX}" STREQUAL "17"))
                set(FASTDDS_REQUIRED_FLAGS "-std=c++17 ${FASTDDS_REQUIRED_FLAGS}")
                add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-std=c++17>)
                set(HAVE_CXX17 1)
                set(HAVE_CXX14 1)
                set(HAVE_CXX1Y 1)
                set(HAVE_CXX11 1)
                set(HAVE_CXX0X 1)
            elseif(NOT SUPPORTS_CXX17 AND FORCE_CXX AND "${FORCE_CXX}" STREQUAL "17")
                message(FATAL_ERROR "Force to support stdc++17 but not supported by the compiler")
            else()
                check_cxx_compiler_flag(-std=c++14 SUPPORTS_CXX14)
                if(SUPPORTS_CXX14 AND (NOT FORCE_CXX OR "${FORCE_CXX}" STREQUAL "14"))
                    set(FASTDDS_REQUIRED_FLAGS "-std=c++14 ${FASTDDS_REQUIRED_FLAGS}")
                    add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-std=c++14>)
                    set(HAVE_CXX14 1)
                    set(HAVE_CXX1Y 1)
                    set(HAVE_CXX11 1)
                    set(HAVE_CXX0X 1)
                elseif(NOT SUPPORTS_CXX14 AND FORCE_CXX AND "${FORCE_CXX}" STREQUAL "14")
                    message(FATAL_ERROR "Force to support stdc++14 but not supported by the compiler")
                else()
                    check_cxx_compiler_flag(-std=c++1y SUPPORTS_CXX1Y)
                    if(SUPPORTS_CXX1Y AND (NOT FORCE_CXX OR "${FORCE_CXX}" STREQUAL "1Y"))
                        set(FASTDDS_REQUIRED_FLAGS "-std=c++1y ${FASTDDS_REQUIRED_FLAGS}")
                        add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-std=c++1y>)
                        set(HAVE_CXX1Y 1)
                        set(HAVE_CXX11 1)
                        set(HAVE_CXX0X 1)
                    elseif(NOT SUPPORTS_CXX1Y AND FORCE_CXX AND "${FORCE_CXX}" STREQUAL "1Y")
                        message(FATAL_ERROR "Force to support stdc++1y but not supported by the compiler")
                    else()
                        check_cxx_compiler_flag(-std=c++11 SUPPORTS_CXX11)
                        if(SUPPORTS_CXX11 AND (NOT FORCE_CXX OR "${FORCE_CXX}" STREQUAL "11"))
                            set(FASTDDS_REQUIRED_FLAGS "-std=c++11 ${FASTDDS_REQUIRED_FLAGS}")
                            add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-std=c++11>)
                            set(HAVE_CXX11 1)
                            set(HAVE_CXX0X 1)
                        elseif(NOT SUPPORTS_CXX11 AND FORCE_CXX AND "${FORCE_CXX}" STREQUAL "11")
                            message(FATAL_ERROR "Force to support stdc++11 but not supported by the compiler")
                        else()
                            check_cxx_compiler_flag(-std=c++0x SUPPORTS_CXX0X)
                            if(SUPPORTS_CXX0X AND (NOT FORCE_CXX OR "${FORCE_CXX}" STREQUAL "0X"))
                                set(FASTDDS_REQUIRED_FLAGS "-std=c++0x ${FASTDDS_REQUIRED_FLAGS}")
                                add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-std=c++0x>)
                                set(HAVE_CXX0X 1)
                            elseif(NOT SUPPORTS_CXX0X AND FORCE_CXX AND "${FORCE_CXX}" STREQUAL "0X")
                                message(FATAL_ERROR "Force to support stdc++0x but not supported by the compiler")
                            else()
                                set(HAVE_CXX0X 0)
                            endif() # c++0x
                        endif() # C++11
                    endif() # C++1Y
                endif() # C++14
            endif() # C++17
        endif() # C++20
    elseif(MSVC OR MSVC_IDE)
        check_cxx_compiler_flag(/std:c++20 SUPPORTS_CXX20)
        set(HAVE_CXX20 0)
        set(HAVE_CXX17 0)
        set(HAVE_CXX14 0)
        set(HAVE_CXX11 0)
        set(HAVE_CXX0X 0)
        if(SUPPORTS_CXX20 AND (NOT FORCE_CXX OR "${FORCE_CXX}" STREQUAL "20"))
            set(FASTDDS_REQUIRED_FLAGS "/std:c++20 ${FASTDDS_REQUIRED_FLAGS}")
            add_compile_options($<$<COMPILE_LANGUAGE:CXX>:/std:c++20>)
            set(HAVE_CXX20 1)
            set(HAVE_CXX17 1)
            set(HAVE_CXX14 1)
            set(HAVE_CXX11 1)
            set(HAVE_CXX0X 1)
        elseif(NOT SUPPORTS_CXX20 AND FORCE_CXX AND "${FORCE_CXX}" STREQUAL "20")
            message(FATAL_ERROR "Force to support stdc++20 but not supported by the compiler")
        else()
            check_cxx_compiler_flag(/std:c++17 SUPPORTS_CXX17)
            if(SUPPORTS_CXX17 AND (NOT FORCE_CXX OR "${FORCE_CXX}" STREQUAL "17"))
                set(FASTDDS_REQUIRED_FLAGS "/std:c++17 ${FASTDDS_REQUIRED_FLAGS}")
                add_compile_options($<$<COMPILE_LANGUAGE:CXX>:/std:c++17>)
                set(HAVE_CXX17 1)
                set(HAVE_CXX14 1)
                set(HAVE_CXX11 1)
                set(HAVE_CXX0X 1)
            elseif(NOT SUPPORTS_CXX17 AND FORCE_CXX AND "${FORCE_CXX}" STREQUAL "17")
                message(FATAL_ERROR "Force to support stdc++17 but not supported by the compiler")
            else()
                check_cxx_compiler_flag(/std:c++14 SUPPORTS_CXX14)
                if(SUPPORTS_CXX14 AND (NOT FORCE_CXX OR "${FORCE_CXX}" STREQUAL "14"))
                    set(FASTDDS_REQUIRED_FLAGS "/std:c++14 ${FASTDDS_REQUIRED_FLAGS}")
                    add_compile_options($<$<COMPILE_LANGUAGE:CXX>:/std:c++14>)
                    set(HAVE_CXX14 1)
                    set(HAVE_CXX11 1)
                    set(HAVE_CXX0X 1)
                elseif(NOT SUPPORTS_CXX14 AND FORCE_CXX AND "${FORCE_CXX}" STREQUAL "14")
                    message(FATAL_ERROR "Force to support stdc++14 but not supported by the compiler")
                else()
                    message(STATUS "The specified C++${FORCE_CXX} option is not supported using compiler default.")
                    set(HAVE_CXX11 1)
                    set(HAVE_CXX0X 1)
                endif() # C++14
            endif() # C++17
        endif() # C++20
    else()
        set(HAVE_CXX11 0)
        set(HAVE_CXX0X 0)
    endif()
endmacro()

macro(check_compile_feature)
    # Check constexpr
    list(FIND CMAKE_CXX_COMPILE_FEATURES "cxx_constexpr" CXX_CONSTEXPR_SUPPORTED)
    if(${CXX_CONSTEXPR_SUPPORTED} GREATER -1)
        set(HAVE_CXX_CONSTEXPR 1)
    else()
        set(HAVE_CXX_CONSTEXPR 0)
    endif()
endmacro()

macro(check_endianness)
    # Test endianness
    include(TestBigEndian)
    test_big_endian(BIG_ENDIAN)
    set(FASTDDS_IS_BIG_ENDIAN_TARGET ${BIG_ENDIAN})
endmacro()

macro(check_msvc_arch)
    if(MSVC_VERSION EQUAL 1700)
        if(CMAKE_CL_64)
            set(MSVC_ARCH "x64Win64VS2012")
        else()
            set(MSVC_ARCH "i86Win32VS2012")
        endif()
    elseif(MSVC_VERSION EQUAL 1800)
        if(CMAKE_CL_64)
            set(MSVC_ARCH "x64Win64VS2013")
        else()
            set(MSVC_ARCH "i86Win32VS2013")
        endif()
    elseif(MSVC_VERSION EQUAL 1900)
        if(CMAKE_CL_64)
            set(MSVC_ARCH "x64Win64VS2015")
        else()
            set(MSVC_ARCH "i86Win32VS2015")
        endif()
    elseif(MSVC_VERSION GREATER 1900)
        if(CMAKE_CL_64)
            set(MSVC_ARCH "x64Win64VS2017")
        else()
            set(MSVC_ARCH "i86Win32VS2017")
        endif()
    else()
        if(CMAKE_CL_64)
            set(MSVC_ARCH "x64Win64VSUnknown")
        else()
            set(MSVC_ARCH "i86Win32VSUnknown")
        endif()
    endif()
endmacro()
