name: 'fetch-fastdds-statistics-backend-repos'
description: 'Fetch Fast DDS and its dependencies'
runs:
  using: "composite"
  steps:
    - id: fetch-fastdds-statistics-backend-repos
      run: |
        wget https://raw.githubusercontent.com/eProsima/Fast-DDS-statistics-backend/master/fastdds_statistics_backend.repos
        vcs import src <  fastdds_statistics_backend.repos
      shell: bash
