# Nightly test workflow for DDS Monitor
name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  reusable_tests:
    strategy:
      fail-fast: false
      matrix:
        version:
        - fastdds_ref: 'v3'
          monitor_ref: '3.x'
          qt_version: '5.15.2'
        - fastdds_ref: 'v3'
          monitor_ref: 'main'
          qt_version: '6.4.2'
    name: reusable_tests
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      custom_version_build: ${{ matrix.version.fastdds_ref }}
      dependencies_artifact_postfix: '_nightly'
      ref: ${{ matrix.version.monitor_ref }}
      qt_version: ${{ matrix.version.qt_version }}
    secrets: inherit
